### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by WhymustIhaveaname** [WhymustIhaveaname/Gongzhu_Arena#1]
Dear Huijun,

Please complete README, introducing Gongzhu as well as its basic rules, and what is this platform aim for. Remember to include the pronunciation of 拱猪 in it so that people can read it correctly.

Thanks,
WhymustIhaveaname

**Comment by soundsinteresting** [comment]
Sure! The basic rules are well explained by wiki though.

**Comment by WhymustIhaveaname** [comment]
I see. good job!
