### ISSUE TITLE
An error while testing server

### ISSUE THREAD

**Issue by dashu233** [WhymustIhaveaname/Gongzhu_Arena#4]
When I create a client and try to send a msg to server, it raise an error:
Exception happened during processing of request from ('223.72.65.195', 2517)
Traceback (most recent call last):
  File "Referee.py", line 71, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
TypeError: __init__() takes 1 positional argument but 4 were given

it seems that there're something wrong in 'MyHTTPServer' class

**Comment by dashu233** [comment]
Ok I'finish this problem by redefine __init()__ of handlerclass

**Comment by WhymustIhaveaname** [comment]
Very good and you can close the issue after you solve it.
